# Generated by Django 3.1.1 on 2020-09-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200919_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_comfirmed',
            new_name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
