# Generated by Django 3.1.1 on 2020-09-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200908_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descriptrion',
            new_name='description',
        ),
    ]
